sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
#    access-key-id: LTAI5tHzX4fMjySKcCoCvYci
#    access-key-secret: vPKhVa4Kux8jUP6fU4614CQ3FW0wiC
#    bucket-name: cangqiongwaimaipbj
#    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5tLdnTdiNnFnqGneXDM2
    access-key-secret: 0nCZE127YACgNukKeIRNLzA5GSAjSb
    bucket-name: sky-take-out-liwenc
    endpoint: oss-cn-guangzhou.aliyuncs.com
